version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: guzzlehttp/psr7
    versions:
    - 1.7.0
    - 1.8.1
  - dependency-name: react/http
    versions:
    - 1.2.0
  - dependency-name: doctrine/dbal
    versions:
    - 3.0.0
